### ISSUE TITLE
Error during registration for TLS account

### ISSUE THREAD

**Issue by schmidt-anja** [tls-kr/tls-app#145]
**Describe the bug**
On my second attempt to create a TLS account I did receive the confirmation e-mail, but I got the following error page upon clicking the verification link: 

![Screenshot 2023-06-15 111054](https://github.com/tls-kr/tls-app/assets/136695999/f4965db8-8acc-4e54-ae57-052e622b52fd)

Windows 11, Opera (64 Bit) Version: 99.0.4788.65 (same result with Chrome)

**Comment by cwittern** [comment]
Hi Anja,
Thank you for checking it out and reporting the problem.  I will have a look.

**Comment by cwittern** [comment]
This has been resolved
