### ISSUE TITLE
Comment Function

### ISSUE THREAD

**Issue by weitubin** [tls-kr/tls-app#15]
**Is your feature request related to a problem? Please describe.**
A feature for commenting on attributions, translations and perhaps even concepts is necessary to make the TLS a platform for discussion and direct exchange - especially if many people are working with it.

**Describe the solution you'd like**
A possible solution could be the use and integration of Stack Exchange (suggested by Christian and John).

**Describe alternatives you've considered**
Another solution could be to program this feature into the TLS, which would require a lot of work and time.

**Comment by cwittern** [comment]
Commenting on concepts is not feasible in the current setup. Closing this for now.  Reopen with specific suggestions if necessary.
