### ISSUE TITLE
Creation of translation file failed

### ISSUE THREAD

**Issue by matchachoco95** [tls-kr/tls-app#153]
**Describe the bug**
When attempting to create a new translation file for a text, the database asks for username and password again and still refuses to create the file. (This was attempted with two different accounts in two different browers; one of the accounts is mine so it 100% has the administrative rights to do so.) 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: FireFox, Google Chrome

**Comment by cwittern** [comment]
Thank you for reporting this.  
There was a problem with permissions on a relevant file, which has been resolved.  
Please try again and see if the problem persists.  If you still can not create a translation file, please tell me which text and which language is involved.

**Comment by matchachoco95** [comment]
It worked just fine for me now, thank you for fixing the issue! :)
