### ISSUE TITLE
Where can I find the texts and translations?

### ISSUE THREAD

**Issue by DarioZ226** [tls-kr/tls-app#159]
I would like to use the texts together with the translations to make bilingual texts to help me learn to read Classical Chinese.

git clone https://github.com/tls-kr/tls-texts.git doesn't work

The old website would display the texts as side-by-side bilingual texts where a translation was available, but currently the translations can be searched but cannot be displayed in any useful way.

**Comment by cwittern** [comment]
Here is the code for the web application that drives hxwd.org.  If you want to see the translations and the texts side by side, some are available to all users, but most require an account. There is a link to apply if you scroll down.

**Comment by DarioZ226** [comment]
I have tried to create an account, but the confirmation e-mail was not sent.

**Comment by cwittern** [comment]
OK, thanks for letting me know.  I will investigate what went wrong.

**Comment by cwittern** [comment]
Hi, I could not find a problem with the processing pipeline for signup requests.  Maybe you can try again?
