### ISSUE TITLE
Switching translation files delayed/not working properly

### ISSUE THREAD

**Issue by matchachoco95** [tls-kr/tls-app#177]
**Describe the bug**
When switching between translation files, the desired translation is not displayed. It takes quite a while for the grey title tile to switch to title of the selected translation, and even then the column remains empty (despite the translation being fully inserted) until refresh. 

**To Reproduce**
1. Go to any given text (in my case with more than two translation files).
2. Try and switch between two different translations (right column in my case).

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome

**Comment by cwittern** [comment]
Hello,
I looked into the issue and I think I identified the problem.  While I ponder a proper solution to the issue, I added a quick fix.  To see if this solves the problem for the time being, please restart your browser and see if the problem persists.

**Comment by matchachoco95** [comment]
It does persist, unfortunately - but thank you so much for your quick reaction! I hope a solution will present itself soon.

**Comment by cwittern** [comment]
Hmm. Does it also persist if you force a complete reload with <shift>+<reload-button>?  The point is that the client side code changed, which is normally cached in the browser, but needs to be reloaded in this case.

**Comment by matchachoco95** [comment]
I updated my browser in between so I think so, but I'll see what happens after I restart the entire laptop. :-) Thank you!

**Comment by cwittern** [comment]
My comment above was mangled in the display (now edited), what I wanted to say was:  Does it also persist if you force a complete reload with ‘shift‘+ ‘reload-button‘? 
Modern browsers seem to try to be smart with caching, but this should be enough to tell the browser to renew everything from the browser.

**Comment by matchachoco95** [comment]
An update on this: after clearing my cache completely, it seems to be working again. Thank you so much for the help!
