### ISSUE TITLE
Occurrences of expressions are no longer counted automatically

### ISSUE THREAD

**Issue by matchachoco95** [tls-kr/tls-app#178]
**Describe the bug**
A bit of a minor issue but it seems as though occurrences of expressions are no longer counted automatically in singular texts. As you can see in the first attached screenshot, I looked for the phrase 而一 in just one text (the 算數書) and every occurrence (even though they clearly appear in different passages) is marked with a 1. Furthermore, on the top part it says "found 1 match" which obviously is not true. 
When searching in all texts, the problem is not present (see second screenshot). 

**To Reproduce**
1. Go in any text. 
2. Look for a specific expression. 

**Expected behavior**
A count of all occurrences should appear at the top, and different occurrences should be counted as such.

**Screenshots**
![image](https://github.com/tls-kr/tls-app/assets/116962137/e976bf03-5544-4ee4-bb3f-747daf64860d)
![image](https://github.com/tls-kr/tls-app/assets/116962137/21de02b7-90a8-4160-992e-40fa0bd637d6)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome

**Comment by cwittern** [comment]
Yes, I know this is a bit of a weird thing.  A while ago, we changed the search code, and as a result 'matches' are counted per paragraph, but the 'matches' are displayed for every line, as before.  So if a paragraph contains several matches, the same number for a match will be displayed multiple times.  It is mainly a confusing interface-issue, but I will see how to resolve it to a more straightforward way of displaying.
