### ISSUE TITLE
The search function seems to be broken

### ISSUE THREAD

**Issue by matchachoco95** [tls-kr/tls-app#183]
**Describe the bug**
Using the search function does not seem to work in any domain (texts, titles, dictionaries, ...). This is what appears when I attempt to look for anything: 

![image](https://github.com/tls-kr/tls-app/assets/116962137/b610ab2f-ea41-4971-9cf6-91fb23abc283)

I was notified by a different user of this and merely reproduced the issue, so I am very sure the problem is not on my side this time. 

**To Reproduce**
1. Go to the front page.
2. Look for any characters in any field.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by matchachoco95** [comment]
Update: it seems to be working just fine again now.

**Comment by cwittern** [comment]
Yeah, I fixed it this morning.
