### ISSUE TITLE
Fail to sign in my account

### ISSUE THREAD

**Issue by Minzhixxx** [tls-kr/tls-app#191]
**Describe the bug**

Hello, sorry for the bother. I applied for an account at TLS a few days ago, and I received a successful letter the day before yesterday. I browsed the link and tried to sign in but failed. I used my email address as username and typed in my password. The website jumped out a notice saying that either my username or my password was wrong. I clearly remembered my password I submitted the other day for it did not take long for my request to be approved thanks to your efficiency. I also tried my name for I fill in the submission chart with my name and also failed to log in. I did not have a github account before, it took me some time to sign up since the Internet is unstable in my area. I wrote an email to the address which sent me the approval email but the letter got rejected.
How can I solve this problem and start to use TLS?

**Screenshots**

![image](https://github.com/tls-kr/tls-app/assets/175219678/f465b9e5-ab7d-4ea6-aa41-3e3374a3c688)

**Comment by cwittern** [comment]
Hmm, I guess I have to manually assign a pw, since we do not yet have an automated reset procedure.

**Comment by cwittern** [comment]
OK, I think I have now found the problem.  Due to an internal bug in the server, it looks like your account has not actually been created.  So please try to signup again.  I will monitor the process and intervene if necessary.
