### ISSUE TITLE
Signup confirmation email not being sent

### ISSUE THREAD

**Issue by justinsilvestre** [tls-kr/tls-app#196]
**Describe the bug**
The signup confirmation email was not sent.

**To Reproduce**
1. Open the signup page at https://hxwd.org/signup.html
2. Complete the form and submit
3. See confirmation message saying an email containing a confirmation link will be sent. No email is actually sent.

**Expected behavior**
An email should be sent after the signup form is successfully submitted.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7fe4e20-0cb6-416d-9a6a-7bb474bcc119)

**Comment by cwittern** [comment]
Thanks for alerting me to this.  This is an issue that is difficult to debug.  I do have received other account requests that went through, so the problem might be elsewhere.  At the moment, I am doing some maintenance work, and will also have a look at the logs and see if I can identify a problem.

**Comment by cwittern** [comment]
OK, I found the root of the problem:  You probably signed up using a gmail account.  It seems that Google requires extra authentication for messages, otherwise they disappear.  
I am now also looking into ways to implement this additional step for gmail...

**Comment by cwittern** [comment]
The issue with gmail has been resolved, please try to sign up again.

**Comment by justinsilvestre** [comment]
It worked! 😃 Thanks for your help!
