### ISSUE TITLE
Attribution list is no longer loaded

### ISSUE THREAD

**Issue by weitubin** [tls-kr/tls-app#21]
**Describe the bug**
If you click on any character, which has a number of possible attributions, the list will no longer load. I do not know if this is related to the previous problem in the dictionary (my prior enquiry).

**To Reproduce**
1. Go to any text in the TLS
2. Click on a character, which has multiple possible attributions (short ones are still working)
3. The list of attributions is not loading anymore

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser Safari
 - Version 13.1.2

**Comment by cwittern** [comment]
Problem has been solved, closing.
