### ISSUE TITLE
Allowing access for members of tls-punc to editing features for specific texts

### ISSUE THREAD

**Issue by cwittern** [tls-kr/tls-app#36]
The group tls-punc is for users who get access to specific features for specific texts. The features should be
- segment splitting and editing ("lock" button)
- Editing of Chinese texts.

Proposed implementation:
- Members of tls-admin curate the access through a special page or dialog, that is shown on the Neibu menu and applies for the text in question.  It should be possible here to select members of tls-punc and assign them to the current text.
-  The list of users allowed for specific texts will be maintained in the file /users/tls-admin/edit-permissions.xml
-  tlslib:navbar-review is responsible for the Neibu menu, when displaying a text (context 'textview') this and applicable sub-menu items should be shown to the appropriate users
- The lock button is shown in tlslib:swl-form-dialog and tlslib:display-seg, in the latter case only when the seg is locked, here we need to check for the appropriate permissions.

**Comment by notiho** [comment]
Working on it in https://github.com/notiho/tls-app/tree/permissions

**Comment by cwittern** [comment]
Thanks, this looks good so far.  I will assign you to this:-)

**Comment by cwittern** [comment]
Thanks for your work.  Looks good, closing this issue now.
