### ISSUE TITLE
Text error messages from tlsapi are not reported

### ISSUE THREAD

**Issue by notiho** [tls-kr/tls-app#51]
In some of the functions in tlsapi.xql, plain string error messages are returned when something goes wrong, e.g. "Error: Text integrity check failed. Can not save edited text." in tlsapi:save-punc. However, they do not appear to affect the status code of the response, and thus are not reported to the user. Is there an intended way to report that something went wrong in tlsapi?

**Comment by cwittern** [comment]
Well, the usual way to handle this in my code is to catch it in the Javascript call and report it there.  But it seems I forgot about this in tlsapi:save-punc.  
The reason for this is, that the jQuery error message is not readable to the user and does not help.... There must be a better way to do this.

**Comment by cwittern** [comment]
I took a look at this today, but forgot to mention this issue.  I'll let it sit for a few days and close if nothing seems amiss.

**Comment by cwittern** [comment]
This seems to be fine for the moment.  A better solution will be available with the move to OpenAPI.
