### ISSUE TITLE
tls-data and tls-texts repositories are missing?

### ISSUE THREAD

**Issue by increpare** [tls-kr/tls-app#77]
**Describe the bug**
This repository requires tsl-data and tsl-texts (mentioned here https://github.com/tls-kr/tls-app ), but neither repositories linked to seem to exist.

**To Reproduce**
1. Go to https://github.com/tls-kr/tls-app
2. Scroll to 'requirement's and try click on tsl-data or tsl-texts, notice that the links are broken.

**Expected behavior**
That the respositories be there.

**Comment by cwittern** [comment]
Thank you for your interest in this project.  The data repositories are private at the moment, they will also be made public in due time, but need a bit of clean up first.  I have made this clear in the Readme now.
