### ISSUE TITLE
Unable to save new text for an already existing translation 

### ISSUE THREAD

**Issue by baianja** [tls-kr/tls-app#98]
When entering text into an already existing translation, I could not save it, and received an error message"Could not save translation. Please create a translation file first." The entered text first still shows, but after refreshing the page, it disappears.

1. Go to 'https://hxwd.org/textview.html?location=KR3f0032_tls_001-p0623a-s3-seg1a&prec=28&foll=2'
2. Enter a line into the column of the  "Translation by Shen Kangshen..."
3. Save

I expected to get a confirmation message that my text has been saved.

**Desktop (please complete the following information):**
 - OS 12.5.1 [Monterey]
 - Browser Chrome
 - Version 108.0.5359.124
 - 
<img width="708" alt="Screenshot 2023-01-06 at 13 22 02" src="https://user-images.githubusercontent.com/120566045/211013967-0b0ed1ea-a80b-4b70-8a39-ea3f548df02a.png">

**Comment by cwittern** [comment]
The screenshot seems to indicate that no translation file has actually been selected (at least not in the slot 2, which is shown here):  It says just "Translation", but if a file is selected, it would give the details of the file here.  Could that be the cause of the problem, or did you actually select a file in slot 1 and type the translation there?

**Comment by cwittern** [comment]
I am glad that it is working now.  This kind of problem is hard to debug and deal with.  If you run into this again, one thing to try is to restart the browser and see if the problem persists.
